package com.ddshop.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-02-07T19:34:03.406+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "DemoServiceService", 
                  wsdlLocation = "http://localhost:8084/pro/ws/weather?wsdl",
                  targetNamespace = "http://service.ddshop.com/") 
public class DemoServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ddshop.com/", "DemoServiceService");
    public final static QName DemoServicePort = new QName("http://service.ddshop.com/", "DemoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8084/pro/ws/weather?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8084/pro/ws/weather?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DemoServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServicePort")
    public DemoService getDemoServicePort() {
        return super.getPort(DemoServicePort, DemoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServicePort")
    public DemoService getDemoServicePort(WebServiceFeature... features) {
        return super.getPort(DemoServicePort, DemoService.class, features);
    }

}
