package com.ddshop.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-02-07T19:34:03.348+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://service.ddshop.com/", name = "DemoService")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://service.ddshop.com/", className = "com.ddshop.service.QueryWeather")
    @WebMethod
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://service.ddshop.com/", className = "com.ddshop.service.QueryWeatherResponse")
    public String queryWeather(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
